version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=1h
      - REDIS_URL=redis://redis:6379
      - ASTRO_ENGINE_URL=${ASTRO_ENGINE_URL}
      - ASTRO_ENGINE_KEY=${ASTRO_ENGINE_KEY}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:19000,http://localhost:19001,http://localhost:19002
      - RATE_LIMIT_WINDOW=15
      - RATE_LIMIT_MAX=100
      - SUBSCRIPTION_PLAN_MONTHLY=${SUBSCRIPTION_PLAN_MONTHLY}
      - SUBSCRIPTION_PLAN_YEARLY=${SUBSCRIPTION_PLAN_YEARLY}
      - SUBSCRIPTION_PLAN_LIFETIME=${SUBSCRIPTION_PLAN_LIFETIME}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
    restart: unless-stopped
    command: npm run dev

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
